### PR TITLE
Initial PTrie merge 

### PR DESCRIPTION
**Pull request by KokosTech**

### CODE REVIEW

**Comment by alvg77** [comment]
Rule #10. The A.c file should first #include its A.h file, and then any other headers required for its code.
http://websites.umich.edu/~eecs381/handouts/CHeaderFileGuidelines.pdf?

**Review by KokosTech — COMMENTED** [review]
Alright

**Review by KokosTech — COMMENTED** [review]
Done

**Review by alvg77 — APPROVED** [review]
good boy

**Comment by KokosTech** [comment]
> good boy
ok-thank-you-omori-ok-thank-you

**Comment by KokosTech** [comment]
ah yeah

**Pull request merged**
